name: workflow_chap_5.3
on:
  push:
    branches:
      - main


jobs:
  prepare_tests:
    runs-on: ubuntu-latest
    outputs:
      HOST: ${{ steps.setup_host.outputs.HOST }}
      DATABASE: ${{ steps.setup_host.outputs.DATABASE }}
    steps:
      - name: Setup host and database
        id: setup_host
        run: |
          echo "HOST=srv1" >> $GITHUB_ENV
          echo "DATABASE=prep002" >> $GITHUB_ENV
          echo "::set-output name=HOST::srv1"
          echo "::set-output name=DATABASE::prep002"

  display_infos:
    runs-on: ubuntu-latest
    needs: prepare_tests
    steps:
      - name: Display HOST and DATABASE
        run: |
          echo "HOST=${{ needs.prepare_tests.outputs.HOST }}"
          echo "DATABASE=${{ needs.prepare_tests.outputs.DATABASE }}"
