name: workflow_chap_4.4
on:
  push:
    branches:
      - main
jobs:
  build_publish_img :
    runs-on: ubuntu-latest

    steps:
      - name: recuper mon code
        uses: actions/checkout@v3

      - name: authentification docker-hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construire et publier l'image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tag: idir2012/dev-exo-4-4:demo

