name: Affichage  README.md

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Afficher le contenu du fichier README.md
        run: |
          cat README.md
