name: workflow_chap_5.4
on:
  push:
    branches:
      - main
jobs:
  testing_phase:
    runs-on: ubuntu-latest

    steps:
      - name: recupuration du tag "3.1.0"
        uses: actions/checkout@v3
        with:
          ref: '3.1.0'
          path: 'tldr-python-client'

      - name: Configuration de Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: pip install -r requirements.txt

      - name: Installation de pytest et pytest-html
        run: pip install pytest pytest-html

      - name: Exécution des tests
        run: |
          pytest --html=report.html
        continue-on-error: true

      - name: Sauvegarde du rapport
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: report.html

      - name: Vérification du statut final du job
        run: | 
          echo "Le statut final du job est : $?"

