name: workflow_chap_4.4
on:
  push:
    branches:
      - main
jobs:
  build_publish_img :
    runs-on: ubuntu-latest

    steps:
      - name: recuper mon code
        uses: actions/checkout@v3

      - name: authentification docker-hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.USER_DOCKER}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{secrets.USER_DOCKER}}/dev-exo-4-4:latest